### ISSUE TITLE
Kodi/Coreelec 115最近几周播放时提示无视频文件，无法播放视频文件

### ISSUE THREAD

**Issue by emvia** [feelfar/115proxy-for-kodi#1]
之前插件一直都可以正常播放原码的4K电影等，但是前几周Kodi和Coreelec 上 插件开始报错说没有视频文件。
请问大佬正在修复吗？
是否可以开放捐赠渠道，愿意为大佬买杯咖啡，感谢！

**Comment by feelfar** [comment]
是，准备直接在github维护了。现初步测试正常，可直接下载源码zip包安装。2020年12月19日 下午12:52，Barney <notifications@github.com>写道：
之前插件一直都可以正常播放原码的4K电影等，但是前几周Kodi和Coreelec 上 插件开始报错说没有视频文件。
请问大佬正在修复吗？
是否可以开放捐赠渠道，愿意为大佬买杯咖啡，感谢！

**Comment by emvia** [comment]
> 是，准备直接在github维护了。现初步测试正常，可直接下载源码zip包安装。2020年12月19日 下午12:52，Barney <notifications@github.com>写道： 之前插件一直都可以正常播放原码的4K电影等，但是前几周Kodi和Coreelec 上 插件开始报错说没有视频文件。 请问大佬正在修复吗？ 是否可以开放捐赠渠道，愿意为大佬买杯咖啡，感谢！ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

昨天下载源码安装了新的版本，已经可以正常播放原码视频了，感谢大佬辛苦维护。
希望大佬能够接受捐助
