### ISSUE TITLE
115源码插件 有办法 支持 kodi 19.4 吗，kodi 18.x历史版本闪退，苦思一天 求助大佬

### ISSUE THREAD

**Issue by xiongzhenglong** [feelfar/115proxy-for-kodi#11]
kodi 目前还是最靠谱的 播放器，无奈 18.x 版本闪退，升级到19.4 ，源码插件无法支持，看不了源码也就没法切换声道，苦恼中

**Comment by feelfar** [comment]
> kodi 目前还是最靠谱的 播放器，无奈 18.x 版本闪退，升级到19.4 ，源码插件无法支持，看不了源码也就没法切换声道，苦恼中

我安卓上试了没问题，你所说的无法支持有什么提示吗？

**Comment by xiongzhenglong** [comment]
是19.4 tv 版本 上安装失败。 不过我昨天在官网下了 20 alpha 版本，可以运行 终于松了一口气
