### ISSUE TITLE
原码插件失效了，大佬看看哈 测试无法播放

### ISSUE THREAD

**Issue by xiongzhenglong** [feelfar/115proxy-for-kodi#12]
获取下载链接失败，提取码不能为空

**Comment by sanguobaby** [comment]
api接口改了，提取都失效了

**Comment by phoenish** [comment]
get into the same trouble, looking forward to repair, thank you.

**Comment by xiongzhenglong** [comment]
大佬们看看，有没有可能修复 不看原码等于 换不了音轨，切不了字幕 不如用 115tv 了

**Comment by feelfar** [comment]
已紧急修复，记得两个插件一并更新

**Comment by wingpig100** [comment]
感谢大佬

**Comment by emvia** [comment]
感谢大佬

**Comment by sjsj5** [comment]
大佬 徒左下角 红圈处的运行是灰色的  是不是有问题 我还是不能播放源码 虬大佬解答 谢谢
![Uploading 226C139C-4BC2-4C4B-A4EC-2DB6383D3895.jpeg…]()

**Comment by sjsj5** [comment]
![280339D0-F51C-4289-97DE-7B341F6BD13D](https://user-images.githubusercontent.com/114943209/193859997-2412e167-9d0c-4553-92d7-c24734e7bf38.jpeg)

**Comment by sjsj5** [comment]
我播放源码还是显示网盘错误 求解决！谢谢
![Uploading D83532DF-BCB3-49FB-856E-84CF9558E24D.jpeg…]()

**Comment by sjsj5** [comment]
![Uploading A6E73690-D32E-4316-8D67-7735BD24C50E.jpeg…]()

**Comment by sjsj5** [comment]
![50CD378D-B592-4B51-8A56-C076956DB826](https://user-images.githubusercontent.com/114943209/193861610-1af7ea21-7fc7-40a6-a49f-387168ca411b.jpeg)

**Comment by sjsj5** [comment]
不知道是不是设置上有什么问题 求大佬指点 再次感谢
