### ISSUE TITLE
6227无法使用

### ISSUE THREAD

**Issue by tonnygjs** [feelfar/115proxy-for-kodi#9]
以前记得局域网IP：6227可以访问的，现在不行了么？我18.9的和19.1的都不行，登录web后报获取文件列表失败，PROXY分别是0.0.2.4和0.3.0.0

**Comment by liuyingsong** [comment]
一样的问题，kodi进入后提示插件错误，但没有找到日志信息。升级了win11。

**Comment by feelfar** [comment]
本地127.0.0.1:6227可以吗？查下是不是防火墙的问题。还有设置内可以改端口，改下试试。

**Comment by tonnygjs** [comment]
可以了，卸载重装插件后正常了
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月28日(星期天) 上午9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [feelfar/115proxy-for-kodi] 6227无法使用 (Issue #9)





 
本地127.0.0.1:6227可以吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuyingsong** [comment]
是防火墙的问题，火绒导致的，谢谢！
